# Use Docker as base image
image: docker:latest

services:
  - docker:dind      # Enable Docker-in-Docker service

variables:
  DOCKER_TLS_CERTDIR: ""  # Required for newer GitLab runners
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull anvarxadja35/solana-sniper-bot:latest

stages:
  - test
  - deploy

# Simple deployment
deploy-job:
  stage: deploy
  script:
    - echo "Add your deployment commands here"
  only:
    - main
  when: manual
