version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: anvarxadja35/solana-sniper-bot:latest
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
