/**
 * Phase 7B.1 — the one standard error shape every /api/v1 response uses
 * (phase7b1.txt §7). Never includes a stack trace, SQL error, provider
 * secret, internal URL, private key, JWT, or raw third-party payload.
 */

import { Response } from "express";
import { z } from "./zodOpenApi";

export const ErrorCode = {
  BAD_REQUEST: "BAD_REQUEST",
  INVALID_MINT: "INVALID_MINT",
  INVALID_ADDRESS: "INVALID_ADDRESS",
  UNAUTHORIZED: "UNAUTHORIZED",
  AUTH_NOT_CONFIGURED: "AUTH_NOT_CONFIGURED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  CHALLENGE_EXPIRED: "CHALLENGE_EXPIRED",
  CHALLENGE_ALREADY_USED: "CHALLENGE_ALREADY_USED",
  WALLET_ALREADY_CLAIMED: "WALLET_ALREADY_CLAIMED",
  RATE_LIMITED: "RATE_LIMITED",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  // Phase 7D.3.2 — paper trading. Each names the one thing the client must do differently.
  IDEMPOTENCY_KEY_REQUIRED: "IDEMPOTENCY_KEY_REQUIRED",
  IDEMPOTENCY_KEY_REUSED: "IDEMPOTENCY_KEY_REUSED",
  QUOTE_EXPIRED: "QUOTE_EXPIRED",
  QUOTE_NOT_FILLABLE: "QUOTE_NOT_FILLABLE",
  SIMULATION_NOT_FOR_QUOTE: "SIMULATION_NOT_FOR_QUOTE",
  SIMULATION_NOT_SUCCESSFUL: "SIMULATION_NOT_SUCCESSFUL",
  // Phase 7D.4 — Practice.
  UNSUPPORTED_CURRENCY: "UNSUPPORTED_CURRENCY",
  NO_PAPER_BALANCE_IN_CURRENCY: "NO_PAPER_BALANCE_IN_CURRENCY",
  INSUFFICIENT_PAPER_BALANCE: "INSUFFICIENT_PAPER_BALANCE",
  INSUFFICIENT_PAPER_HOLDING: "INSUFFICIENT_PAPER_HOLDING",
  PLAN_MISMATCH: "PLAN_MISMATCH",
  PLAN_NOT_CLOSEABLE: "PLAN_NOT_CLOSEABLE",
  ALREADY_REVIEWED: "ALREADY_REVIEWED",
  // Phase 7D.4 §7 — vanity handoff.
  UNSUPPORTED_CHAIN: "UNSUPPORTED_CHAIN",
  VANITY_NONE_AVAILABLE: "VANITY_NONE_AVAILABLE",
  RESERVATION_EXPIRED: "RESERVATION_EXPIRED",
  ALREADY_CONSUMED: "ALREADY_CONSUMED",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export const ErrorEnvelopeSchema = z
  .object({
    error: z.object({
      code: z.string(),
      message: z.string(),
      requestId: z.string(),
    }),
  })
  .openapi("ErrorEnvelope");

export type ErrorEnvelope = z.infer<typeof ErrorEnvelopeSchema>;

const STATUS_FOR_CODE: Record<ErrorCode, number> = {
  BAD_REQUEST: 400,
  INVALID_MINT: 400,
  INVALID_ADDRESS: 400,
  UNAUTHORIZED: 401,
  AUTH_NOT_CONFIGURED: 503,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CHALLENGE_EXPIRED: 410,
  CHALLENGE_ALREADY_USED: 409,
  WALLET_ALREADY_CLAIMED: 409,
  RATE_LIMITED: 429,
  INTERNAL_ERROR: 500,
  IDEMPOTENCY_KEY_REQUIRED: 400,
  IDEMPOTENCY_KEY_REUSED: 422,
  QUOTE_EXPIRED: 409,
  QUOTE_NOT_FILLABLE: 409,
  SIMULATION_NOT_FOR_QUOTE: 409,
  SIMULATION_NOT_SUCCESSFUL: 409,
  UNSUPPORTED_CURRENCY: 400,
  NO_PAPER_BALANCE_IN_CURRENCY: 409,
  INSUFFICIENT_PAPER_BALANCE: 409,
  INSUFFICIENT_PAPER_HOLDING: 409,
  PLAN_MISMATCH: 409,
  PLAN_NOT_CLOSEABLE: 409,
  ALREADY_REVIEWED: 409,
  UNSUPPORTED_CHAIN: 400,
  VANITY_NONE_AVAILABLE: 409,
  RESERVATION_EXPIRED: 409,
  ALREADY_CONSUMED: 409,
};

export function sendError(res: Response, code: ErrorCode, message: string, requestId: string, status: number = STATUS_FOR_CODE[code]): void {
  const body: ErrorEnvelope = { error: { code, message, requestId } };
  res.status(status).json(body);
}
